spring: 
  profiles: 
    active: 
    - dev 
---
server:
  port: 3355
spring: 
  profiles: div      #开发环境
  application: 
    name: super-config-dev
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/ 
      
---
spring: 
  profiles: test     #测试环境
  application: 
    name: super-config-test
---
server: 
  port: 7001
spring: 
  profiles: eureka7001     #测试环境
  application: 
    name: super-config-test-eureka7001
eureka: 
  instance: 
    hostname: www.eureka7001.com
  client: 
    register-with-eureka: false            #false表示不向注册中心注册自己
    fetch-registry: false                  #false表示自己端就是祖册中心，我的职责是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/                        #单机
      #defaultZone: http://www.eureka7002.com:7002/eureka/ #,http://www.eureka7003.com:7003/eureka/    #集群
   
---
server: 
 port: 8001

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml 
  type-aliases-package: com.supermap.vo 
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml 

spring: 
  application: 
    profiles: dept8001     #测试环境
    name: supermap-dept
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:   #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
      #defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/ #,http://eureka7003.com:7003/eureka/
  instance: 
    instance-id: super-dept:8001
    prefer-ip-address: true

info: 
  app.name: supermap-dept
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: ￥project.version$

