spring: 
  profiles: 
    active: 
	- dev 
---
spring: 
  profiles: div      #开发环境
  application: 
    name: super-config-dev
---
spring: 
  profiles: test     #测试环境
  application: 
    name: super-config-test
